import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { CheckResult } from "@/lib/checks/types";
import { computeScore } from "@/lib/score";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", color: "#1a1a1a" },
  header: { borderBottom: "2pt solid #1a1a1a", paddingBottom: 12, marginBottom: 24 },
  title: { fontSize: 22, fontWeight: "bold" },
  subtitle: { fontSize: 11, color: "#666", marginTop: 4 },
  scoreRow: { flexDirection: "row", alignItems: "center", gap: 18, marginBottom: 14 },
  scoreBig: { fontSize: 46, fontWeight: "bold" },
  scoreLabel: { fontSize: 11, color: "#666" },
  grade: { fontSize: 14, fontWeight: "bold" },
  verdict: { fontSize: 11, color: "#333", marginBottom: 18 },
  catHeader: {
    marginTop: 14,
    marginBottom: 6,
    paddingBottom: 4,
    borderBottom: "1pt solid #ddd",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  catName: { fontSize: 12, fontWeight: "bold" },
  catScore: { fontSize: 10, color: "#666" },
  row: { flexDirection: "row", paddingVertical: 5, borderBottom: "0.5pt solid #eee" },
  status: { width: 50, fontWeight: "bold", fontSize: 9 },
  severity: { width: 60, fontSize: 8, color: "#666" },
  name: { width: 160, fontSize: 10 },
  message: { flex: 1, fontSize: 9, color: "#444" },
  footer: { marginTop: 20, paddingTop: 8, borderTop: "0.5pt solid #ddd", fontSize: 8, color: "#888" },
  pass: { color: "#10b981" },
  warn: { color: "#f59e0b" },
  fail: { color: "#ef4444" },
  skip: { color: "#999" },
});

function statusStyle(s: string) {
  if (s === "PASS") return styles.pass;
  if (s === "WARN") return styles.warn;
  if (s === "FAIL") return styles.fail;
  return styles.skip;
}

export function Report({
  owner,
  repo,
  results,
}: {
  owner: string;
  repo: string;
  results: CheckResult[];
}) {
  const score = computeScore(results);
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>nextcheck — Security Audit</Text>
          <Text style={styles.subtitle}>
            {owner}/{repo} · {new Date().toISOString().split("T")[0]} · {results.length} checks
          </Text>
        </View>

        <View style={styles.scoreRow}>
          <Text style={[styles.scoreBig, statusStyle(score.score >= 75 ? "PASS" : score.score >= 40 ? "WARN" : "FAIL")]}>
            {score.score}/100
          </Text>
          <View>
            <Text style={styles.grade}>Grade {score.grade}</Text>
            <Text style={styles.scoreLabel}>
              {score.pass} pass · {score.warn} warn · {score.fail} fail · {score.skip} skip
            </Text>
          </View>
        </View>
        <Text style={styles.verdict}>{score.verdict}</Text>

        {score.byCategory.map((cat) => (
          <View key={cat.category} wrap={false}>
            <View style={styles.catHeader}>
              <Text style={styles.catName}>{cat.category}</Text>
              <Text style={styles.catScore}>
                {cat.score}/100 · {cat.results.length} check{cat.results.length !== 1 ? "s" : ""}
              </Text>
            </View>
            {cat.results.map((r) => (
              <View key={r.id} style={styles.row}>
                <Text style={[styles.status, statusStyle(r.status)]}>{r.status}</Text>
                <Text style={styles.severity}>{r.severity}</Text>
                <Text style={styles.name}>{r.name}</Text>
                <Text style={styles.message}>{r.message}</Text>
              </View>
            ))}
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by nextcheck (https://nextcheck-six.vercel.app) · Free public security audit for
          Next.js + Supabase repos · Built end-to-end via AI orchestration.
        </Text>
      </Page>
    </Document>
  );
}
